[package]
name = "ghayb"
version = "0.1.0"
edition = "2021"

[dependencies]
druid = "0.8.3"
eframe = "0.31.1"
reqwest = { version = "0.11", features = ["blocking"] }
tokio = { version = "1", features = ["full"] }
scraper = "0.13"
url = "2.2"
